//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventory.Shared.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Product.
        /// </summary>
        public static string Action_AddProduct {
            get {
                return ResourceManager.GetString("Action.AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Action_Close {
            get {
                return ResourceManager.GetString("Action.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm.
        /// </summary>
        public static string Action_Confirm {
            get {
                return ResourceManager.GetString("Action.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string Action_Edit {
            get {
                return ResourceManager.GetString("Action.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        public static string Action_Logout {
            get {
                return ResourceManager.GetString("Action.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product Expense.
        /// </summary>
        public static string Action_ProductExpense {
            get {
                return ResourceManager.GetString("Action.ProductExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product Income.
        /// </summary>
        public static string Action_ProductIncome {
            get {
                return ResourceManager.GetString("Action.ProductIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reports.
        /// </summary>
        public static string Action_Reports {
            get {
                return ResourceManager.GetString("Action.Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string Common_Information {
            get {
                return ResourceManager.GetString("Common.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading....
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        public static string Common_Success {
            get {
                return ResourceManager.GetString("Common.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        public static string Common_Warning {
            get {
                return ResourceManager.GetString("Common.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key Metrics.
        /// </summary>
        public static string Dashboard_KeyMetrics {
            get {
                return ResourceManager.GetString("Dashboard.KeyMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quick Actions.
        /// </summary>
        public static string Dashboard_QuickActions {
            get {
                return ResourceManager.GetString("Dashboard.QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Track key metrics and manage your warehouse in real-time..
        /// </summary>
        public static string Dashboard_Welcome {
            get {
                return ResourceManager.GetString("Dashboard.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string Field_Description {
            get {
                return ResourceManager.GetString("Field.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string Field_Email {
            get {
                return ResourceManager.GetString("Field.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Field_Name {
            get {
                return ResourceManager.GetString("Field.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Field_Password {
            get {
                return ResourceManager.GetString("Field.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello, {0}!.
        /// </summary>
        public static string Greeting_Hello {
            get {
                return ResourceManager.GetString("Greeting.Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Language.
        /// </summary>
        public static string Language_Select {
            get {
                return ResourceManager.GetString("Language.Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About company (opens in new window).
        /// </summary>
        public static string Navigation_AboutCompany {
            get {
                return ResourceManager.GetString("Navigation.AboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Administration.
        /// </summary>
        public static string Navigation_Administration {
            get {
                return ResourceManager.GetString("Navigation.Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audit.
        /// </summary>
        public static string Navigation_Audit {
            get {
                return ResourceManager.GetString("Navigation.Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catalog.
        /// </summary>
        public static string Navigation_Catalog {
            get {
                return ResourceManager.GetString("Navigation.Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Debug.
        /// </summary>
        public static string Navigation_Debug {
            get {
                return ResourceManager.GetString("Navigation.Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string Navigation_Home {
            get {
                return ResourceManager.GetString("Navigation.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main content area.
        /// </summary>
        public static string Navigation_MainContent {
            get {
                return ResourceManager.GetString("Navigation.MainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main navigation menu.
        /// </summary>
        public static string Navigation_MainMenu {
            get {
                return ResourceManager.GetString("Navigation.MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page content.
        /// </summary>
        public static string Navigation_PageContent {
            get {
                return ResourceManager.GetString("Navigation.PageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reference Data.
        /// </summary>
        public static string Navigation_ReferenceData {
            get {
                return ResourceManager.GetString("Navigation.ReferenceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reports.
        /// </summary>
        public static string Navigation_Reports {
            get {
                return ResourceManager.GetString("Navigation.Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Requests.
        /// </summary>
        public static string Navigation_Requests {
            get {
                return ResourceManager.GetString("Navigation.Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle menu.
        /// </summary>
        public static string Navigation_ToggleMenu {
            get {
                return ResourceManager.GetString("Navigation.ToggleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Users.
        /// </summary>
        public static string Navigation_Users {
            get {
                return ResourceManager.GetString("Navigation.Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warehouses.
        /// </summary>
        public static string Navigation_Warehouses {
            get {
                return ResourceManager.GetString("Navigation.Warehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reports in progress.
        /// </summary>
        public static string Page_ReportsInProgress {
            get {
                return ResourceManager.GetString("Page.ReportsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warehouses in progress.
        /// </summary>
        public static string Page_WarehousesInProgress {
            get {
                return ResourceManager.GetString("Page.WarehousesInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category.
        /// </summary>
        public static string Product_Category {
            get {
                return ResourceManager.GetString("Product.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manufacturer.
        /// </summary>
        public static string Product_Manufacturer {
            get {
                return ResourceManager.GetString("Product.Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min: {0} | Max: {1}.
        /// </summary>
        public static string Product_MinMax {
            get {
                return ResourceManager.GetString("Product.MinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SKU.
        /// </summary>
        public static string Product_SKU {
            get {
                return ResourceManager.GetString("Product.SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Categories.
        /// </summary>
        public static string Stats_Categories {
            get {
                return ResourceManager.GetString("Stats.Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Low Stock.
        /// </summary>
        public static string Stats_LowStock {
            get {
                return ResourceManager.GetString("Stats.LowStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на require replenishment.
        /// </summary>
        public static string Stats_LowStockSubLabel {
            get {
                return ResourceManager.GetString("Stats.LowStockSubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manufacturers.
        /// </summary>
        public static string Stats_Manufacturers {
            get {
                return ResourceManager.GetString("Stats.Manufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Out of Stock.
        /// </summary>
        public static string Stats_OutOfStock {
            get {
                return ResourceManager.GetString("Stats.OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на need to order.
        /// </summary>
        public static string Stats_OutOfStockSubLabel {
            get {
                return ResourceManager.GetString("Stats.OutOfStockSubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Products.
        /// </summary>
        public static string Stats_TotalProducts {
            get {
                return ResourceManager.GetString("Stats.TotalProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warehouses.
        /// </summary>
        public static string Stats_Warehouses {
            get {
                return ResourceManager.GetString("Stats.Warehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на administrator.
        /// </summary>
        public static string User_DefaultName {
            get {
                return ResourceManager.GetString("User.DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please correct the following errors:.
        /// </summary>
        public static string Validation_ErrorSummary {
            get {
                return ResourceManager.GetString("Validation.ErrorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter a valid email address.
        /// </summary>
        public static string Validation_InvalidEmail {
            get {
                return ResourceManager.GetString("Validation.InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum length is {0} characters.
        /// </summary>
        public static string Validation_MaxLength {
            get {
                return ResourceManager.GetString("Validation.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum length is {0} characters.
        /// </summary>
        public static string Validation_MinLength {
            get {
                return ResourceManager.GetString("Validation.MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This field is required.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation.Required", resourceCulture);
            }
        }
    }
}
