CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "Role" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "RefreshToken" text,
        "RefreshTokenExpiry" timestamp with time zone,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text,
        "IsActive" boolean NOT NULL,
        "ParentCategoryId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Categories_Categories_ParentCategoryId" FOREIGN KEY ("ParentCategoryId") REFERENCES "Categories" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "InventoryTransaction" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "ProductName" text NOT NULL,
        "TransactionType" text NOT NULL,
        "Reason" text,
        "Reference" text,
        "LocationId" integer,
        "LocationName" text,
        "UserId" text,
        "UserName" text,
        "TransactionDate" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_InventoryTransaction" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "Locations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text,
        "IsActive" boolean NOT NULL,
        "ParentLocationId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Locations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Locations_Locations_ParentLocationId" FOREIGN KEY ("ParentLocationId") REFERENCES "Locations" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "Manufacturers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Manufacturers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "NotificationRules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "EventType" character varying(50) NOT NULL,
        "NotificationType" character varying(50) NOT NULL,
        "Category" character varying(50) NOT NULL,
        "Condition" text NOT NULL,
        "Template" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "Priority" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone,
        "CreatedBy" text,
        CONSTRAINT "PK_NotificationRules" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "NotificationTemplates" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "EventType" character varying(50) NOT NULL,
        "SubjectTemplate" text NOT NULL,
        "BodyTemplate" text NOT NULL,
        "NotificationType" character varying(50) NOT NULL,
        "Category" character varying(50) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_NotificationTemplates" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "Product" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "SKU" text NOT NULL,
        "Description" text,
        "Unit" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CategoryId" integer NOT NULL,
        "CategoryName" text NOT NULL,
        "ManufacturerId" integer NOT NULL,
        "ManufacturerName" text NOT NULL,
        "ProductModelId" integer NOT NULL,
        "ProductModelName" text NOT NULL,
        "ProductGroupId" integer NOT NULL,
        "ProductGroupName" text NOT NULL,
        "Note" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Product" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "ProductGroups" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ProductGroups" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "ProductTags" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ProductTags" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "UnitOfMeasures" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(50) NOT NULL,
        "Symbol" character varying(10) NOT NULL,
        "Description" character varying(200),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_UnitOfMeasures" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "User" (
        "Id" text NOT NULL,
        "UserName" text NOT NULL,
        "Email" text NOT NULL,
        "EmailConfirmed" boolean NOT NULL,
        "Role" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_User" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "Warehouses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text,
        "Address" text NOT NULL,
        "ContactInfo" text,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Warehouses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "AuditLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EntityName" character varying(100) NOT NULL,
        "EntityId" character varying(50) NOT NULL,
        "Action" character varying(50) NOT NULL,
        "ActionType" integer NOT NULL,
        "EntityType" character varying(100) NOT NULL,
        "Changes" text,
        "RequestId" character varying(100),
        "UserId" character varying(450) NOT NULL,
        "Username" character varying(100),
        "OldValues" character varying(4000),
        "NewValues" character varying(4000),
        "Description" character varying(1000),
        "Timestamp" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "IpAddress" character varying(45) NOT NULL,
        "UserAgent" character varying(500) NOT NULL,
        "HttpMethod" character varying(10),
        "Url" character varying(500),
        "StatusCode" integer,
        "Duration" bigint,
        "Metadata" text,
        "Severity" character varying(20) NOT NULL,
        "IsSuccess" boolean NOT NULL,
        "ErrorMessage" character varying(1000),
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AuditLogs_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "SignalRConnections" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ConnectionId" character varying(450) NOT NULL,
        "UserId" character varying(450) NOT NULL,
        "UserName" character varying(100),
        "UserRole" character varying(50),
        "UserAgent" character varying(500),
        "IpAddress" character varying(45),
        "ConnectedAt" timestamp with time zone NOT NULL,
        "LastActivityAt" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "SubscribedGroups" character varying(1000),
        "SubscribedNotificationTypes" character varying(1000),
        CONSTRAINT "PK_SignalRConnections" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SignalRConnections_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "ProductModels" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "ManufacturerId" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ProductModels" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductModels_Manufacturers_ManufacturerId" FOREIGN KEY ("ManufacturerId") REFERENCES "Manufacturers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "NotificationPreferences" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" character varying(450) NOT NULL,
        "EventType" character varying(50) NOT NULL,
        "EmailEnabled" boolean NOT NULL,
        "InAppEnabled" boolean NOT NULL,
        "PushEnabled" boolean NOT NULL,
        "MinPriority" integer,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_NotificationPreferences" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_NotificationPreferences_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "Notifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(200) NOT NULL,
        "Message" character varying(1000) NOT NULL,
        "Type" character varying(50) NOT NULL,
        "Category" character varying(50) NOT NULL,
        "ActionUrl" character varying(100),
        "ActionText" character varying(50),
        "IsRead" boolean NOT NULL,
        "IsArchived" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "ReadAt" timestamp with time zone,
        "ExpiresAt" timestamp with time zone,
        "UserId" text,
        "UserName" text,
        "ProductId" integer,
        "ProductName" text,
        "TransactionId" integer,
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notifications_InventoryTransaction_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "InventoryTransaction" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Notifications_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Product" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Notifications_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "Products" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "SKU" text NOT NULL,
        "Description" text,
        "UnitOfMeasureId" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CategoryId" integer NOT NULL,
        "ManufacturerId" integer NOT NULL,
        "ProductModelId" integer NOT NULL,
        "ProductGroupId" integer NOT NULL,
        "Note" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Products_Manufacturers_ManufacturerId" FOREIGN KEY ("ManufacturerId") REFERENCES "Manufacturers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Products_ProductGroups_ProductGroupId" FOREIGN KEY ("ProductGroupId") REFERENCES "ProductGroups" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Products_ProductModels_ProductModelId" FOREIGN KEY ("ProductModelId") REFERENCES "ProductModels" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Products_UnitOfMeasures_UnitOfMeasureId" FOREIGN KEY ("UnitOfMeasureId") REFERENCES "UnitOfMeasures" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "InventoryTransactions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "WarehouseId" integer NOT NULL,
        "Type" integer NOT NULL,
        "Date" timestamp with time zone NOT NULL,
        "UserId" text NOT NULL,
        "LocationId" integer,
        "Description" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_InventoryTransactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InventoryTransactions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_InventoryTransactions_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES "Locations" ("Id"),
        CONSTRAINT "FK_InventoryTransactions_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_InventoryTransactions_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "ProductHistories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "Date" timestamp with time zone NOT NULL,
        "OldQuantity" integer NOT NULL,
        "NewQuantity" integer NOT NULL,
        "UserId" text NOT NULL,
        "Description" text,
        CONSTRAINT "PK_ProductHistories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductHistories_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProductHistories_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE TABLE "ProductProductTags" (
        "ProductTagsId" integer NOT NULL,
        "ProductsId" integer NOT NULL,
        CONSTRAINT "PK_ProductProductTags" PRIMARY KEY ("ProductTagsId", "ProductsId"),
        CONSTRAINT "FK_ProductProductTags_ProductTags_ProductTagsId" FOREIGN KEY ("ProductTagsId") REFERENCES "ProductTags" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProductProductTags_Products_ProductsId" FOREIGN KEY ("ProductsId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_Categories_ParentCategoryId" ON "Categories" ("ParentCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_InventoryTransactions_LocationId" ON "InventoryTransactions" ("LocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_InventoryTransactions_ProductId" ON "InventoryTransactions" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_InventoryTransactions_UserId" ON "InventoryTransactions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_InventoryTransactions_WarehouseId" ON "InventoryTransactions" ("WarehouseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_Locations_ParentLocationId" ON "Locations" ("ParentLocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE UNIQUE INDEX "IX_NotificationPreferences_UserId_EventType" ON "NotificationPreferences" ("UserId", "EventType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_Notifications_ProductId" ON "Notifications" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_Notifications_TransactionId" ON "Notifications" ("TransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_ProductHistories_ProductId" ON "ProductHistories" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_ProductHistories_UserId" ON "ProductHistories" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_ProductModels_ManufacturerId" ON "ProductModels" ("ManufacturerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_ProductProductTags_ProductsId" ON "ProductProductTags" ("ProductsId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_Products_ManufacturerId" ON "Products" ("ManufacturerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_Products_ProductGroupId" ON "Products" ("ProductGroupId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_Products_ProductModelId" ON "Products" ("ProductModelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_Products_UnitOfMeasureId" ON "Products" ("UnitOfMeasureId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE INDEX "IX_SignalRConnections_UserId" ON "SignalRConnections" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    CREATE UNIQUE INDEX "IX_UnitOfMeasures_Symbol" ON "UnitOfMeasures" ("Symbol");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919051410_InitialCreate_20250118') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250919051410_InitialCreate_20250118', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250921185844_RemoveVapidPushSubscriptions') THEN
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1 FROM information_schema.tables 
            WHERE table_schema = 'public' AND table_name = 'PushSubscriptions'
        ) THEN
            DROP TABLE "PushSubscriptions";
        END IF;
    END$$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250921185844_RemoveVapidPushSubscriptions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250921185844_RemoveVapidPushSubscriptions', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250921202335_Warehouse_LocationRef') THEN
    ALTER TABLE "Warehouses" DROP COLUMN "Address";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250921202335_Warehouse_LocationRef') THEN
    ALTER TABLE "Warehouses" ADD "LocationId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250921202335_Warehouse_LocationRef') THEN
    CREATE INDEX "IX_Warehouses_LocationId" ON "Warehouses" ("LocationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250921202335_Warehouse_LocationRef') THEN
    ALTER TABLE "Warehouses" ADD CONSTRAINT "FK_Warehouses_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES "Locations" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250921202335_Warehouse_LocationRef') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250921202335_Warehouse_LocationRef', '8.0.11');
    END IF;
END $EF$;
COMMIT;

